"""ORM models for the orders service.

This module defines the SQLAlchemy models used to represent orders and
order items. The models are intentionally small for the scaffold and
are designed to be used by the service's CRUD and API handlers.

Primary models:
- ``Order``: a top-level order record containing user and status
    information and the total amount.
- ``OrderItem``: a line-item associated with an order that records the
    purchased book id, quantity and price information at purchase time.

Notes:
        - Primary keys are UUID4 strings generated by :func:`gen_uuid`.
        - Consider adding explicit relationships, indexes and constraints for
            production use, and manage schema changes using migrations (Alembic)
            rather than ``create_all``.
"""

import datetime
import uuid

from sqlalchemy import Column, DateTime, Float, ForeignKey, Integer, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


def gen_uuid():
    """Generate a UUID4 string for use as a primary key.

    Returns:
        str: a UUID4 string.
    """
    return str(uuid.uuid4())


class Order(Base):
    __tablename__ = "orders"
    """A customer order record.

    Fields:
        id (str): UUID4 primary key as string.
        user_id (str): UUID of the user who placed the order.
        status (str): current order status (pending, processing, completed, cancelled).
        total_amount (float): total cost of the order at creation time.
        created_at (datetime): creation timestamp.
        updated_at (datetime): last update timestamp.
    """
    id = Column(UUID(as_uuid=False), primary_key=True, default=gen_uuid)
    user_id = Column(UUID(as_uuid=False), nullable=False)
    status = Column(String, nullable=False)
    total_amount = Column(Float, nullable=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow)


class OrderItem(Base):
    __tablename__ = "order_items"
    """A single line item belonging to an order.

    Fields:
        id (str): UUID4 primary key as string.
        order_id (str): foreign key to ``orders.id``.
        book_id (str): UUID of the book purchased.
        quantity (int): number of units purchased.
        price_at_purchase (float): price per unit at purchase time.
        subtotal (float): computed subtotal (quantity * price_at_purchase).
    """
    id = Column(UUID(as_uuid=False), primary_key=True, default=gen_uuid)
    order_id = Column(UUID(as_uuid=False), ForeignKey("orders.id"), nullable=False)
    book_id = Column(UUID(as_uuid=False), nullable=False)
    quantity = Column(Integer, nullable=False)
    price_at_purchase = Column(Float, nullable=False)
    subtotal = Column(Float, nullable=False)
